services:
    app:
        image: 'backend-playground'
        build:
          context: .
          dockerfile: Dockerfile
        ports:
        - '8081:8081'
        depends_on:
        - mysql-db
        profiles:
          - full
        environment:
        - 'SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/storytack'
        - 'SPRING_DATASOURCE_USERNAME=${DB_USER}'
        - 'SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}'
        - 'SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver'
        - 'SPRING_JPA_HIBERNATE_DDL_AUTO=update'
    mysql-db:
      image: 'mysql:latest'
      environment:
        - 'MYSQL_DATABASE=storytack'
        - 'MYSQL_PASSWORD=${DB_PASSWORD}'
        - 'MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}'
        - 'MYSQL_USER=${DB_USER}'
      ports:
        - '3306:3306'
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        interval: 10s
        timeout: 5s
        retries: 5
