name: 'Cache and Install Docker Compose'
description: 'Caches and installs Docker Compose'
inputs:
  path:
    description: 'Path to the repository.  Must end with a forward slash.'
    required: true
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Cache Docker Compose
      uses: actions/cache@v4
      with:
        path: /usr/local/bin/docker-compose
        key: ${{ runner.os }}-docker-compose-${{ hashFiles(format('{0}**/docker-compose.yml', inputs.path)) }}
        restore-keys: |
          ${{ runner.os }}-docker-compose-

    - name: Install Docker Compose
      run: |
        if [ ! -f /usr/local/bin/docker-compose ]; then
          sudo apt-get update
          sudo apt-get install -y docker-compose
        fi
      shell: bash